kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: dmi
 labels:
  eidf/user: s2745300-infk8s
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 300Gi
 storageClassName: csi-cephfs-sc
